DELETE FROM drink;
ALTER SEQUENCE drink_id_seq RESTART WITH 1;

INSERT INTO
drink (id, title, recipe)
VALUES
(1, 'black coffee', '{"color":"black", "name":"black", "parts":1}'),
(2, 'coffee', '{"color":"brown", "name":"espresso", "parts":1}'),
(3, 'milk', '{"color":"beige", "name":"latte", "parts":2}');
-- (3, 'cappuccino', '{"color":"brown", "name":"cappuccino", "parts":2}')
-- (3, 'french', '{"color":"white", "name":"french", "parts":1}')
